on:
push:
branches:["main"]
paths:
-"biotestesite/**"
workflow_dispatch:
jobs:
deploy:
runs-on: ubuntu-latest
steps:
-uses: actions/checkout@v4
-name: FTP Deploy Localweb
uses: locaweb/ftp-deploy@1.0.0
with
host: ${{secrets.HOST}}
user: ${{secrets.USER}}
password: ${{secrets.PASS}}
localdir:"biotestesite"
remote: "site"
